[build]
builder = "DOCKERFILE"
dockerfilePath = "src-api/Dockerfile"

[deploy]
startCommand = "code-warrior-api"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
